name: booking_app
description: Booking Service User Interface

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  floating_navbar:
  intl: ^0.16.1
  flutter_staggered_grid_view: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/data/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
